name: Master  # The name of your Workflow

on:
  schedule:  # Tells Github to run this Workflow every 12h
    - cron: "0 */12 * * *"

jobs:
  scrape-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.7'
      # Tells Github to run the file `extract_data_script.py` from your repository
      - name: Run Master
        run: python extract_data_script.py
